### ISSUE TITLE
Search problems on iPhone

### ISSUE THREAD

**Issue by Chuck217** [ltguillaume/music-folder-player#56]
Let me start by saying I love MusicFolderPlayer -- The only issue I am experiencing is when someone is trying to search from an iPhone, they are able to only type the first letter on their phone, and then the search stops working -- I have not seen this issue on Android -- I have had users try both safari and chrome -- Any thoughts or suggestions?

**Comment by ltGuillaume** [comment]
Thanks for the kind words! 😃

First question that comes to mind: is `instantfilter` set to `0` or something else?

**Comment by Chuck217** [comment]
Where is that line located?  Maybe I'm out of date?

**Comment by Chuck217** [comment]
I didn't have a music.ini,  so I downloaded your latest -- Re installed -- the InstantFilter is currently set to 0 -- I have made no changed to music.ini

**Comment by Chuck217** [comment]
Some of my iPhone users have just confirmed they are now able to search!!!

**Comment by ltGuillaume** [comment]
Cool! I wonder what commit ("version") you were on before this. I think I made a change once concerning this, but I do think it has been quite some time ago.
