### ISSUE TITLE
How to add multiple source paths to music folder?

### ISSUE THREAD

**Issue by Zovereign** [ltguillaume/music-folder-player#59]
How to add multiple source paths to music folder?
Currently, I just run to 1 path. Don't know how to add more.

**Comment by ltguillaume** [comment]
Hmz I haven't really made that available. Maybe you can create multiple symbolic links inside the library folder? Or wouldn't that suffice in this case?

**Comment by Zovereign** [comment]
Alright, I give it a try then. Thank you.
