### ISSUE TITLE
No Show "Playlist Option" Up

### ISSUE THREAD

**Issue by mario9999999** [ltguillaume/music-folder-player#61]
If "sharing = false" -----> music.ini

That config affected to "Playlist Option"
Playlist Menu (Playlist Option) disappeared
When Click "Playlist" option did not show up anything

Please fix that issue
Thanks a lot ^^

**Comment by ltguillaume** [comment]
Thx for reporting! Fixed!

**Comment by mario9999999** [comment]
You're welcome ^^
