### ISSUE TITLE
No Showing "Log Change Focuscolor"

### ISSUE THREAD

**Issue by mario9999999** [ltguillaume/music-folder-player#62]
When use shortcut key C to change color, Log Debug didn't show information change color anything after focusblue
![image](https://github.com/ltguillaume/music-folder-player/assets/68627112/875e149f-c794-44eb-9fde-3f00acc97626)

Please fix that issue
Thanks ^^

**Comment by ltguillaume** [comment]
Thanks! It's fixed now, but apparently Codeberg still has some issues from yesterday's hardware failure, so I can't push it just yet.

**Comment by ltguillaume** [comment]
Done.
